before_install:
  - sudo aptitude -y -q install curl make libgc-dev libsdl1.2-dev libglew1.6-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin
  - git clone --depth=1 git://github.com/nddrylliog/ooc-sdl.git

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v sdl-gl.ooc -o=travis/sdl-gl

